### ISSUE TITLE
The blogpost about the dear imgui needs to be updated

### ISSUE THREAD

**Issue by keszegrobert** [conan-io/examples2#142]
Thank you for your work! I don't know if this is an issue for the people here, but maybe you can reach out to somebody who can fix this.

The links in the blogpost about the use of dear imgui are a little bit outdated.
https://blog.conan.io/2019/06/26/An-introduction-to-the-Dear-ImGui-library.html

The link to the examples points here:
https://github.com/conan-io/examples2/tree/new_imgui_example/examples/libraries/imgui/introduction
which gives a 404

The conan2 example lives here:
https://github.com/conan-io/examples2/tree/main/examples/libraries/imgui/introduction

**Comment by memsharded** [comment]
Hi @keszegrobert 

Thanks for reporting this.

I am submitting https://github.com/conan-io/conan-io.github.io/pull/264 to fix it
